[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.8.2", default-features = false, features = [
    "uuid",
    "chrono",
    "json",
] }
serde = { version = "1.0", features = ["derive"] }